apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-provisioning
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://monitoring-kube-prometheus-prometheus:9090
        jsonData:
          timeInterval: 15s
      - name: Loki
        type: loki
        access: proxy
        url: http://monitoring-loki:3100
        jsonData:
          derivedFields:
            - matcherRegex: (?:trace_id|traceID)=(\w+)
              name: TraceID
              url: '$${__value.raw}'

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Default Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
