{{- if .Values.prometheusIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  {{- with .Values.prometheusIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.prometheusIngress.ingressClassName }}
  ingressClassName: {{ .Values.prometheusIngress.ingressClassName }}
  {{- end }}
  {{- if .Values.prometheusIngress.tls }}
  tls:
    {{- range .Values.prometheusIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.prometheusIngress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-kube-prometheus-prometheus
                port:
                  number: 9090
    {{- end }}
{{- end }}
